apiVersion: storage.k8s.io/v1 
kind: StorageClass # Cluster Scope
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
# allowVolumeExpansion: true
# parameters:
#   type: gp3                    # GP3 volumes (better performance, lower cost than gp2)
