---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
  namespace: prod
  labels:
    app: mysql-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
        - name: mysql-exporter
          image: prom/mysqld-exporter:v0.15.1
          args:
            - --mysqld.address=mysql:3306
            - --mysqld.username=root
            - --no-collect.slave_status
          env:
            - name: MYSQLD_EXPORTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 9104
              name: metrics
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  namespace: prod
  labels:
    app: mysql-exporter
spec:
  selector:
    app: mysql-exporter
  ports:
    - port: 9104
      targetPort: 9104
      name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-exporter-monitor
  namespace: prod
  labels:
    app: mysql-exporter
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: mysql-exporter
  endpoints:
    - port: metrics
      interval: 30s
